package main

type Session struct {
	// The id of the session, generated by stores.
	ID string 
	// Values contains the user-data for the session
	Values map[string]interface{}
	Options *Options
	IsNew bool
	Store PGStore
	name string
}

func (session *Session) Name() string {
	return session.name
}